"""Tests for the code preprocessor."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.models import Language, SourceFile
from src.preprocessor import preprocess, _is_generated, _mostly_binary, _clean_source


def _sf(content: str, path: str, lang: Language = Language.JAVA) -> SourceFile:
    return SourceFile(
        path=f"/root/{path}", relative_path=path, language=lang,
        content=content, content_hash="abc123",
        size_bytes=len(content.encode()), line_count=content.count("\n") + 1,
    )


# ── Source file filtering ──

def test_java_source_kept():
    files = [_sf("public class A {}", "src/A.java", Language.JAVA)]
    result = preprocess(files)
    assert len(result.source_files) == 1

def test_python_source_kept():
    files = [_sf("class A: pass", "src/A.py", Language.PYTHON)]
    result = preprocess(files)
    assert len(result.source_files) == 1

def test_go_source_kept():
    files = [_sf("package main", "cmd/main.go", Language.GO)]
    result = preprocess(files)
    assert len(result.source_files) == 1

def test_js_source_kept():
    files = [_sf("class A {}", "src/A.js", Language.JAVASCRIPT)]
    result = preprocess(files)
    assert len(result.source_files) == 1

def test_ts_source_kept():
    files = [_sf("class A {}", "src/A.ts", Language.TYPESCRIPT)]
    result = preprocess(files)
    assert len(result.source_files) == 1


# ── Config files ──

def test_xml_is_config():
    files = [_sf("<root/>", "pom.xml")]
    result = preprocess(files)
    assert len(result.config_files) == 1
    assert len(result.source_files) == 0

def test_yaml_is_config():
    files = [_sf("key: value", "config.yaml")]
    result = preprocess(files)
    assert len(result.config_files) == 1

def test_json_is_config():
    files = [_sf('{"key": 1}', "package.json")]
    result = preprocess(files)
    assert len(result.config_files) == 1

def test_properties_is_config():
    files = [_sf("key=value", "app.properties")]
    result = preprocess(files)
    assert len(result.config_files) == 1

def test_sql_is_config():
    files = [_sf("SELECT * FROM users;", "schema.sql")]
    result = preprocess(files)
    assert len(result.config_files) == 1


# ── Skipped files ──

def test_generated_file_skipped():
    content = "// Auto-generated by codegen. Do not edit.\nclass Foo {}"
    files = [_sf(content, "src/gen/Foo.java", Language.JAVA)]
    result = preprocess(files)
    assert len(result.source_files) == 0
    assert result.skipped_reasons.get("generated", 0) >= 1

def test_binary_extension_skipped():
    # .class files wouldn't normally be loaded, but test the logic
    files = [_sf("PK\x03\x04", "build/Foo.class")]
    result = preprocess(files)
    assert len(result.source_files) == 0
    assert len(result.config_files) == 0

def test_tiny_non_source_skipped():
    files = [_sf("x", "tmp/x")]
    result = preprocess(files)
    assert len(result.source_files) == 0
    assert len(result.config_files) == 0


# ── Generated file detection ──

def test_is_generated_various_markers():
    assert _is_generated("// Auto-generated code\n// Do not edit\nclass A {}")
    assert _is_generated("// Generated by protobuf\nmessage Foo {}")
    assert _is_generated("# This file is generated by setup.py")
    assert _is_generated("// @generated\n// DO NOT MODIFY")

def test_is_not_generated():
    assert not _is_generated("public class UserService {\n    // Normal code\n}")
    assert not _is_generated("def hello():\n    return 'world'")


# ── Binary detection ──

def test_mostly_binary():
    assert _mostly_binary("\x00\x01\x02\x03\x04\x05\x06\x07" * 100)

def test_not_mostly_binary():
    assert not _mostly_binary("public class Foo {\n    void bar() {}\n}")


# ── Source cleaning ──

def test_clean_source_removes_excess_blank_lines():
    code = "class A {\n\n\n\n\n    void bar() {}\n}"
    cleaned = _clean_source(code)
    # Should have at most 2 consecutive blank lines
    assert "\n\n\n\n" not in cleaned

def test_clean_source_removes_trailing_whitespace():
    code = "class A {   \n    void bar() {}  \n}"
    cleaned = _clean_source(code)
    for line in cleaned.split("\n"):
        assert line == line.rstrip()


# ── Full pipeline ──

def test_preprocess_mixed_files():
    files = [
        _sf("public class A {}", "src/A.java", Language.JAVA),
        _sf("class B: pass", "src/B.py", Language.PYTHON),
        _sf("<root/>", "pom.xml"),
        _sf("key=val", "app.properties"),
        _sf("SELECT 1;", "init.sql"),
        _sf("# README", "README.md"),
        _sf("// Auto-generated\n// Do not edit\nclass C {}", "src/gen/C.java", Language.JAVA),
    ]
    result = preprocess(files)
    assert len(result.source_files) == 2  # A.java and B.py
    assert len(result.config_files) == 4  # pom.xml, app.properties, init.sql, README.md
    assert result.skipped_count >= 1      # gen/C.java
