"""
Mock LLM responses for testing without API calls.
Used when CODEBASE_MOCK=true in .env
"""

MOCK_CHUNK = {
    "file_path": "src/main/java/com/example/app/services/catalog/controller/ActorController.java",
    "summary": "REST controller providing CRUD endpoints for Actor entities with HATEOAS support.",
    "purpose": "Expose actor management functionality through RESTful API endpoints.",
    "key_methods": [
        {"name": "getActors", "signature": "public ResponseEntity<CollectionModel<ActorDto>> getActors(Pageable pageable)",
         "description": "Retrieves a paginated list of all actors", "complexity": 3},
        {"name": "getActor", "signature": "public ResponseEntity<ActorDto> getActor(@PathVariable Long id)",
         "description": "Fetches a specific actor by ID with 404 handling", "complexity": 2},
        {"name": "createActor", "signature": "public ResponseEntity<ActorDto> createActor(@RequestBody ActorDto dto)",
         "description": "Creates a new actor entry in the database", "complexity": 4},
    ],
    "dependencies": ["ActorService", "ActorRepresentationModelAssembler"],
    "complexity_score": 4,
    "complexity_notes": "Moderate complexity from multiple endpoint handlers, HATEOAS assembly, and pagination.",
}

MOCK_SYNTHESIS = {
    "project_overview": {
        "name": "Spring REST Sakila",
        "description": "A Spring Boot REST API that provides CRUD operations for the Sakila sample database, which models a DVD rental store. The application exposes RESTful endpoints for managing films, actors, customers, rentals, and other entities in the DVD rental domain.",
        "purpose": "To demonstrate building RESTful APIs with Spring Boot by implementing a complete backend for a DVD rental management system. The project serves as a reference implementation for Spring Data JPA, REST controllers, HATEOAS, and service layer patterns.",
        "architecture": "Layered architecture following the MVC pattern with clear separation of concerns:\n\n* Controller Layer: REST endpoints that handle HTTP requests and responses using Spring Web MVC\n* Service Layer: Business logic and transaction management with interface-based design\n* Repository Layer: Data access using Spring Data JPA with QueryDSL for type-safe dynamic queries\n* Entity Layer: JPA entities mapped to MySQL database tables with MapStruct for DTO conversion\n\nCross-cutting concerns handled by:\n* JWT-based stateless authentication via Spring Security\n* Global exception handling with standardized error responses\n* MDC logging for request tracing\n* Redis caching for performance",
        "domain": "DVD rental management",
        "primary_language": "Java",
        "framework": "Spring Boot",
        "technologies": [
            "Java 17", "Spring Boot 3.x", "Spring Data JPA", "Spring Web MVC",
            "Spring Security", "Spring HATEOAS", "Hibernate ORM", "QueryDSL",
            "MapStruct", "MySQL Database", "Redis Cache", "JWT Authentication",
            "Gradle Build Tool", "Sakila Sample Database",
        ],
        "modules": [
            "controller", "service", "repository", "entity",
            "mapper", "configuration", "security", "exception_handling",
        ],
        "total_files": 200,
        "total_lines_of_code": 11200,
    },
    "architectural_insights": {
        "layers": ["Controller -> Service -> Repository -> JPA -> MySQL"],
        "design_patterns": ["Repository Pattern", "DTO Pattern", "HATEOAS", "MapStruct Mapper"],
        "cross_cutting_concerns": ["JWT Authentication", "Global Exception Handling", "MDC Logging", "Redis Caching"],
        "data_flow": "HTTP -> SecurityFilter -> Controller -> Service -> Repository -> JPA -> MySQL -> Response",
        "integration_points": ["MySQL", "Redis"],
        "strengths": [
            "Clean separation of concerns", "Consistent DTO mapping with MapStruct",
            "HATEOAS for RESTful representation", "Type-safe queries with QueryDSL",
        ],
        "areas_for_improvement": [
            "Add integration tests", "Implement rate limiting",
            "Add OpenAPI documentation", "Consider API versioning",
        ],
    },
    "services": [
        {"service_name": "catalog", "description": "Film and actor catalog management",
         "purpose": "Manage the film/actor catalog including CRUD and search",
         "classes": ["ActorController", "FilmController", "ActorServiceImpl", "FilmServiceImpl"],
         "api_endpoints": [
             {"method": "GET", "path": "/api/v1/actors", "description": "List actors", "handler": "getActorList"},
             {"method": "GET", "path": "/api/v1/actors/{id}", "description": "Get actor", "handler": "getActor"},
             {"method": "POST", "path": "/api/v1/actors", "description": "Create actor", "handler": "addActor"},
             {"method": "GET", "path": "/api/v1/films", "description": "List films", "handler": "getFilmList"},
             {"method": "GET", "path": "/api/v1/films/{id}", "description": "Get film details", "handler": "getFilmDetails"},
         ],
         "complexity_notes": ["Uses QueryDSL for dynamic actor search", "HATEOAS representation model assembly"]},
        {"service_name": "auth", "description": "Authentication and authorization",
         "purpose": "JWT-based user authentication and security context management",
         "classes": ["LoginController", "JwtAuthenticationFilter", "JwtTokenProvider"],
         "api_endpoints": [
             {"method": "POST", "path": "/api/v1/auth/login", "description": "Login and get JWT token", "handler": "userLogin"},
         ],
         "complexity_notes": ["Stateless JWT authentication", "Token validation on every request"]},
        {"service_name": "customer", "description": "Customer management",
         "purpose": "Manage customer accounts, details, and relationships to stores",
         "classes": ["CustomerController", "CustomerServiceImpl"],
         "api_endpoints": [
             {"method": "GET", "path": "/api/v1/customers", "description": "List customers", "handler": "getCustomerList"},
             {"method": "GET", "path": "/api/v1/customers/{id}", "description": "Get customer details", "handler": "getCustomerDetails"},
         ],
         "complexity_notes": []},
        {"service_name": "rental", "description": "Rental operations",
         "purpose": "Handle film rentals, returns, and inventory management",
         "classes": ["RentalController", "RentalServiceImpl"],
         "api_endpoints": [
             {"method": "GET", "path": "/api/v1/rentals", "description": "List rentals", "handler": "getRentalList"},
             {"method": "POST", "path": "/api/v1/rentals", "description": "Rent a DVD", "handler": "rentDvd"},
             {"method": "PUT", "path": "/api/v1/rentals/return", "description": "Return a DVD", "handler": "returnDvd"},
         ],
         "complexity_notes": ["Complex inventory management", "Date calculations for rental periods"]},
        {"service_name": "payment", "description": "Payment processing",
         "purpose": "Record and manage rental payments",
         "classes": ["PaymentController", "PaymentServiceImpl"],
         "api_endpoints": [
             {"method": "GET", "path": "/api/v1/payments", "description": "List payments", "handler": "getPaymentList"},
         ],
         "complexity_notes": []},
        {"service_name": "location", "description": "Location management",
         "purpose": "Manage addresses, cities, and countries",
         "classes": ["LocationController", "LocationServiceImpl"],
         "api_endpoints": [
             {"method": "GET", "path": "/api/v1/addresses", "description": "List addresses", "handler": "getAddressList"},
             {"method": "GET", "path": "/api/v1/cities", "description": "List cities", "handler": "getCityList"},
         ],
         "complexity_notes": []},
        {"service_name": "staff", "description": "Staff management",
         "purpose": "Manage store staff accounts and assignments",
         "classes": ["StaffController", "StaffServiceImpl"],
         "api_endpoints": [
             {"method": "GET", "path": "/api/v1/staff", "description": "List staff", "handler": "getStaffList"},
         ],
         "complexity_notes": []},
        {"service_name": "store", "description": "Store and reporting",
         "purpose": "Manage stores, staff assignments, and sales reports",
         "classes": ["StoreController", "ReportController"],
         "api_endpoints": [
             {"method": "GET", "path": "/api/v1/stores", "description": "List stores", "handler": "getStoreList"},
             {"method": "GET", "path": "/api/v1/reports/sales-by-category", "description": "Sales by category", "handler": "reportSalesByCategory"},
             {"method": "GET", "path": "/api/v1/reports/sales-by-store", "description": "Sales by store", "handler": "reportSalesByStore"},
         ],
         "complexity_notes": ["Custom QueryDSL queries for sales aggregation"]},
    ],
    "key_classes": [
        {"name": "ActorController", "file_path": "src/main/java/com/example/app/services/catalog/controller/ActorController.java",
         "role": "controller", "summary": "REST controller exposing Sakila Actor APIs with HATEOAS support.",
         "methods": [
             {"name": "getActorList", "signature": "ResponseEntity<CollectionModel<ActorDto>> getActorList(Pageable pageable)",
              "description": "Retrieves paginated list of all actors", "http_method": "GET", "path": "/api/v1/actors", "estimated_complexity": 2},
             {"name": "getActor", "signature": "ResponseEntity<ActorDto> getActor(@PathVariable Integer actorId)",
              "description": "Fetches a specific actor by ID", "http_method": "GET", "path": "/api/v1/actors/{id}", "estimated_complexity": 2},
             {"name": "addActor", "signature": "ResponseEntity<Void> addActor(@RequestBody ActorDto.ActorRequest model)",
              "description": "Creates a new actor", "http_method": "POST", "path": "/api/v1/actors", "estimated_complexity": 5},
             {"name": "updateActor", "signature": "ResponseEntity<Void> updateActor(@PathVariable Integer actorId, @RequestBody ActorDto.ActorRequest model)",
              "description": "Updates an existing actor", "http_method": "PUT", "path": "/api/v1/actors/{id}", "estimated_complexity": 5},
             {"name": "deleteActor", "signature": "ResponseEntity<Void> deleteActor(@PathVariable Integer actorId)",
              "description": "Deletes an actor", "http_method": "DELETE", "path": "/api/v1/actors/{id}", "estimated_complexity": 2},
             {"name": "getActorDetails", "signature": "ResponseEntity<ActorDetailsDto> getActorDetails(@PathVariable Integer actorId)",
              "description": "Gets detailed actor info with film list", "http_method": "GET", "path": "/api/v1/actors/{id}/details", "estimated_complexity": 5},
             {"name": "getActorFilmList", "signature": "ResponseEntity<CollectionModel<FilmDto>> getActorFilmList(@PathVariable Integer actorId)",
              "description": "Gets films for a specific actor", "http_method": "GET", "path": "/api/v1/actors/{id}/films", "estimated_complexity": 5},
             {"name": "searchActorByName", "signature": "ResponseEntity<CollectionModel<ActorDto>> searchActorByName(@RequestBody Map<String,String> input)",
              "description": "Searches actors by name", "http_method": "POST", "path": "/api/v1/actors/search", "estimated_complexity": 5},
         ]},
        {"name": "FilmController", "file_path": "src/main/java/com/example/app/services/catalog/controller/FilmController.java",
         "role": "controller", "summary": "REST controller exposing Sakila Film APIs.",
         "methods": [
             {"name": "getFilmList", "signature": "ResponseEntity<CollectionModel<FilmDto>> getFilmList(Pageable pageable)",
              "description": "Retrieves paginated list of all films", "http_method": "GET", "path": "/api/v1/films", "estimated_complexity": 2},
             {"name": "getFilm", "signature": "ResponseEntity<FilmDto> getFilm(@PathVariable Integer filmId)",
              "description": "Fetches a specific film by ID", "http_method": "GET", "path": "/api/v1/films/{id}", "estimated_complexity": 2},
             {"name": "addFilm", "signature": "ResponseEntity<Void> addFilm(@RequestBody FilmDto.FilmRequest model)",
              "description": "Creates a new film", "http_method": "POST", "path": "/api/v1/films", "estimated_complexity": 5},
             {"name": "updateFilm", "signature": "ResponseEntity<Void> updateFilm(@PathVariable Integer filmId, @RequestBody FilmDto.FilmRequest model)",
              "description": "Updates an existing film", "http_method": "PUT", "path": "/api/v1/films/{id}", "estimated_complexity": 5},
             {"name": "deleteFilm", "signature": "ResponseEntity<Void> deleteFilm(@PathVariable Integer filmId)",
              "description": "Deletes a film", "http_method": "DELETE", "path": "/api/v1/films/{id}", "estimated_complexity": 2},
             {"name": "getFilmDetails", "signature": "ResponseEntity<FilmDetailsDto> getFilmDetails(@PathVariable Integer filmId)",
              "description": "Gets detailed film info with actors and categories", "http_method": "GET", "path": "/api/v1/films/{id}/details", "estimated_complexity": 5},
             {"name": "getFilmActorList", "signature": "ResponseEntity<CollectionModel<ActorDto>> getFilmActorList(@PathVariable Integer filmId)",
              "description": "Gets actors for a specific film", "http_method": "GET", "path": "/api/v1/films/{id}/actors", "estimated_complexity": 5},
         ]},
        {"name": "CustomerController", "file_path": "src/main/java/com/example/app/services/customer/controller/CustomerController.java",
         "role": "controller", "summary": "REST controller exposing Sakila Customer APIs.",
         "methods": [
             {"name": "getCustomerList", "signature": "ResponseEntity<CollectionModel<CustomerDto>> getCustomerList(Pageable pageable)",
              "description": "Retrieves paginated list of customers", "http_method": "GET", "path": "/api/v1/customers", "estimated_complexity": 2},
             {"name": "getCustomer", "signature": "ResponseEntity<CustomerDto> getCustomer(@PathVariable Integer customerId)",
              "description": "Fetches a specific customer by ID", "http_method": "GET", "path": "/api/v1/customers/{id}", "estimated_complexity": 2},
             {"name": "addCustomer", "signature": "ResponseEntity<Void> addCustomer(@RequestBody CustomerDto.CustomerRequest model)",
              "description": "Creates a new customer", "http_method": "POST", "path": "/api/v1/customers", "estimated_complexity": 5},
             {"name": "getCustomerDetails", "signature": "ResponseEntity<CustomerDetailsDto> getCustomerDetails(@PathVariable Integer customerId)",
              "description": "Gets detailed customer info with rentals and payments", "http_method": "GET", "path": "/api/v1/customers/{id}/details", "estimated_complexity": 5},
             {"name": "getCustomerPaymentList", "signature": "ResponseEntity<CollectionModel<PaymentDto>> getCustomerPaymentList(@PathVariable Integer customerId)",
              "description": "Gets payments for a customer", "http_method": "GET", "path": "/api/v1/customers/{id}/payments", "estimated_complexity": 5},
             {"name": "getCustomerRentalList", "signature": "ResponseEntity<CollectionModel<RentalDto>> getCustomerRentalList(@PathVariable Integer customerId)",
              "description": "Gets rentals for a customer", "http_method": "GET", "path": "/api/v1/customers/{id}/rentals", "estimated_complexity": 5},
         ]},
        {"name": "RentalController", "file_path": "src/main/java/com/example/app/services/rental/controller/RentalController.java",
         "role": "controller", "summary": "REST controller exposing Sakila Rental APIs.",
         "methods": [
             {"name": "getRentalList", "signature": "ResponseEntity<CollectionModel<RentalDto>> getRentalList(Pageable pageable)",
              "description": "Retrieves paginated list of rentals", "http_method": "GET", "path": "/api/v1/rentals", "estimated_complexity": 2},
             {"name": "rentDvd", "signature": "ResponseEntity<Void> rentDvd(@RequestBody RentalDto.RentalCreateRequest model)",
              "description": "Creates a new rental transaction", "http_method": "POST", "path": "/api/v1/rentals", "estimated_complexity": 8},
             {"name": "returnDvd", "signature": "ResponseEntity<Void> returnDvd(@RequestBody Map<String,String> input)",
              "description": "Processes a DVD return", "http_method": "PUT", "path": "/api/v1/rentals/return", "estimated_complexity": 8},
             {"name": "getRental", "signature": "ResponseEntity<RentalDto> getRental(@PathVariable Integer rentalId)",
              "description": "Fetches a specific rental by ID", "http_method": "GET", "path": "/api/v1/rentals/{id}", "estimated_complexity": 2},
         ]},
        {"name": "LocationController", "file_path": "src/main/java/com/example/app/services/location/controller/LocationController.java",
         "role": "controller", "summary": "REST controller exposing Sakila Location APIs for addresses, cities, and countries.",
         "methods": [
             {"name": "getAddressList", "signature": "ResponseEntity<CollectionModel<AddressDto>> getAddressList(Pageable pageable)",
              "description": "Retrieves paginated list of addresses", "http_method": "GET", "path": "/api/v1/addresses", "estimated_complexity": 2},
             {"name": "getAddress", "signature": "ResponseEntity<AddressDto> getAddress(@PathVariable Integer addressId)",
              "description": "Fetches a specific address by ID", "http_method": "GET", "path": "/api/v1/addresses/{id}", "estimated_complexity": 2},
             {"name": "getCityList", "signature": "ResponseEntity<CollectionModel<CityDto>> getCityList(Pageable pageable)",
              "description": "Retrieves paginated list of cities", "http_method": "GET", "path": "/api/v1/cities", "estimated_complexity": 2},
         ]},
        {"name": "PaymentController", "file_path": "src/main/java/com/example/app/services/payment/controller/PaymentController.java",
         "role": "controller", "summary": "REST controller exposing Sakila Payment APIs.",
         "methods": [
             {"name": "getPaymentList", "signature": "ResponseEntity<CollectionModel<PaymentDto>> getPaymentList(Pageable pageable)",
              "description": "Retrieves paginated list of payments", "http_method": "GET", "path": "/api/v1/payments", "estimated_complexity": 2},
             {"name": "getPayment", "signature": "ResponseEntity<PaymentDto> getPayment(@PathVariable Integer paymentId)",
              "description": "Fetches a specific payment by ID", "http_method": "GET", "path": "/api/v1/payments/{id}", "estimated_complexity": 2},
         ]},
        {"name": "StoreController", "file_path": "src/main/java/com/example/app/services/store/controller/StoreController.java",
         "role": "controller", "summary": "REST controller exposing Sakila Store APIs.",
         "methods": [
             {"name": "getStoreList", "signature": "ResponseEntity<CollectionModel<StoreDto>> getStoreList(Pageable pageable)",
              "description": "Retrieves paginated list of stores", "http_method": "GET", "path": "/api/v1/stores", "estimated_complexity": 2},
             {"name": "getStore", "signature": "ResponseEntity<StoreDto> getStore(@PathVariable Integer storeId)",
              "description": "Fetches a specific store by ID", "http_method": "GET", "path": "/api/v1/stores/{id}", "estimated_complexity": 2},
             {"name": "getStoreStaffList", "signature": "ResponseEntity<CollectionModel<StaffDto>> getStoreStaffList(@PathVariable Integer storeId)",
              "description": "Gets staff for a specific store", "http_method": "GET", "path": "/api/v1/stores/{id}/staff", "estimated_complexity": 5},
         ]},
        {"name": "ReportController", "file_path": "src/main/java/com/example/app/services/store/controller/ReportController.java",
         "role": "controller", "summary": "REST controller exposing Sakila Report APIs for sales analytics.",
         "methods": [
             {"name": "reportSalesByCategory", "signature": "ResponseEntity<CollectionModel<CategorySalesDto>> reportSalesByCategory()",
              "description": "Generates sales report grouped by film category", "http_method": "GET", "path": "/api/v1/reports/sales-by-category", "estimated_complexity": 5},
             {"name": "reportSalesByStore", "signature": "ResponseEntity<CollectionModel<StoreSalesDto>> reportSalesByStore()",
              "description": "Generates sales report grouped by store", "http_method": "GET", "path": "/api/v1/reports/sales-by-store", "estimated_complexity": 5},
         ]},
        {"name": "StaffController", "file_path": "src/main/java/com/example/app/services/staff/controller/StaffController.java",
         "role": "controller", "summary": "REST controller exposing Sakila Staff APIs.",
         "methods": [
             {"name": "getStaffList", "signature": "ResponseEntity<CollectionModel<StaffDto>> getStaffList(Pageable pageable)",
              "description": "Retrieves paginated list of staff", "http_method": "GET", "path": "/api/v1/staff", "estimated_complexity": 2},
             {"name": "getStaff", "signature": "ResponseEntity<StaffDto> getStaff(@PathVariable Integer staffId)",
              "description": "Fetches a specific staff member by ID", "http_method": "GET", "path": "/api/v1/staff/{id}", "estimated_complexity": 2},
         ]},
        {"name": "RentalServiceImpl", "file_path": "src/main/java/com/example/app/services/rental/service/RentalServiceImpl.java",
         "role": "service", "summary": "Service implementing rental business logic with inventory management and date calculations.",
         "methods": [
             {"name": "createRental", "signature": "RentalDto createRental(RentalDto dto)",
              "description": "Creates rental with inventory validation", "http_method": "", "path": None, "estimated_complexity": 8},
             {"name": "returnRental", "signature": "RentalDto returnRental(Long id)",
              "description": "Processes return with inventory update", "http_method": "", "path": None, "estimated_complexity": 8},
         ]},
        {"name": "JwtAuthenticationFilter", "file_path": "src/main/java/com/example/app/common/security/JwtAuthenticationFilter.java",
         "role": "security", "summary": "JWT filter validating tokens on every request and setting the security context.",
         "methods": [
             {"name": "doFilterInternal", "signature": "void doFilterInternal(HttpServletRequest req, HttpServletResponse res, FilterChain chain)",
              "description": "Validates JWT token from Authorization header", "http_method": "", "path": None, "estimated_complexity": 8},
         ]},
        {"name": "GlobalExceptionHandler", "file_path": "src/main/java/com/example/app/common/exception/GlobalExceptionHandler.java",
         "role": "exception_handling", "summary": "Centralized exception handler converting exceptions to standardized HTTP error responses.",
         "methods": [
             {"name": "handleNotFound", "signature": "ResponseEntity<ErrorResponseDto> handleNotFound(ResourceNotFoundException ex)",
              "description": "Handles 404 errors with structured response", "http_method": "", "path": None, "estimated_complexity": 2},
             {"name": "handleValidation", "signature": "ResponseEntity<ErrorResponseDto> handleValidation(MethodArgumentNotValidException ex)",
              "description": "Handles validation errors with field details", "http_method": "", "path": None, "estimated_complexity": 5},
         ]},
    ],
    "key_methods": [
        {"name": "getActorList", "signature": "ResponseEntity<CollectionModel<ActorDto>> getActorList(Pageable pageable)",
         "description": "Retrieves a paginated list of all actors with HATEOAS links.", "complexity": 3,
         "file_path": "src/main/java/com/example/app/services/catalog/controller/ActorController.java"},
        {"name": "getFilmDetails", "signature": "ResponseEntity<FilmDetailsDto> getFilmDetails(@PathVariable Integer filmId)",
         "description": "Fetches detailed film information including actors, categories, and special features.", "complexity": 4,
         "file_path": "src/main/java/com/example/app/services/catalog/controller/FilmController.java"},
        {"name": "userLogin", "signature": "ResponseEntity<Void> userLogin(@RequestBody AuthorityDto.Login login)",
         "description": "Authenticates a user and returns a JWT token for subsequent API calls.", "complexity": 5,
         "file_path": "src/main/java/com/example/app/services/auth/controller/LoginController.java"},
        {"name": "rentDvd", "signature": "ResponseEntity<Void> rentDvd(@RequestBody RentalDto.RentalCreateRequest model)",
         "description": "Creates a new rental transaction. Validates inventory availability and sets rental dates.", "complexity": 7,
         "file_path": "src/main/java/com/example/app/services/rental/controller/RentalController.java"},
        {"name": "returnDvd", "signature": "ResponseEntity<Void> returnDvd(@RequestBody Map<String,String> input)",
         "description": "Processes a rental return by updating the return date and incrementing inventory count.", "complexity": 6,
         "file_path": "src/main/java/com/example/app/services/rental/controller/RentalController.java"},
        {"name": "searchActors", "signature": "Page<ActorEntity> searchActors(String name, Pageable pageable)",
         "description": "Custom QueryDSL repository method for dynamic actor search with multiple optional filters.", "complexity": 5,
         "file_path": "src/main/java/com/example/app/services/catalog/repository/custom/CustomActorRepositoryImpl.java"},
        {"name": "doFilterInternal", "signature": "void doFilterInternal(HttpServletRequest req, HttpServletResponse res, FilterChain chain)",
         "description": "JWT authentication filter that validates the token from the Authorization header on every request.", "complexity": 6,
         "file_path": "src/main/java/com/example/app/common/security/JwtAuthenticationFilter.java"},
        {"name": "reportSalesByCategory", "signature": "ResponseEntity<CollectionModel<CategorySalesDto>> reportSalesByCategory()",
         "description": "Generates a sales report grouped by film category using custom QueryDSL aggregation.", "complexity": 5,
         "file_path": "src/main/java/com/example/app/services/store/controller/ReportController.java"},
        {"name": "getCustomerDetails", "signature": "ResponseEntity<CustomerDetailsDto> getCustomerDetails(@PathVariable Integer customerId)",
         "description": "Fetches detailed customer information including address, store, and rental history.", "complexity": 4,
         "file_path": "src/main/java/com/example/app/services/customer/controller/CustomerController.java"},
        {"name": "handleNotFound", "signature": "ResponseEntity<ErrorResponseDto> handleNotFound(ResourceNotFoundException ex)",
         "description": "Global exception handler for 404 errors with structured error response.", "complexity": 3,
         "file_path": "src/main/java/com/example/app/common/exception/GlobalExceptionHandler.java"},
    ],
    "complexity_metrics": {
        "total_files": 200, "total_lines": 11200, "total_classes": 85, "total_functions": 320,
        "avg_methods_per_class": 3.8, "avg_complexity_score": 4.2,
        "largest_files": ["FilmDto.java", "Country.java", "RentalDto.java", "StaffDto.java", "AddressDto.java"],
        "most_complex_classes": ["CustomActorRepositoryImpl", "FilmEntity", "RentalServiceImpl"],
    },
    "cross_cutting_patterns": [
        "All entities use MapStruct for DTO conversion",
        "Consistent use of Spring HATEOAS for REST resources",
        "QueryDSL for type-safe dynamic queries",
        "Global exception handling with standardized error responses",
        "JWT-based stateless authentication",
    ],
    "recommendations": [
        "Add OpenAPI 3.0 documentation with springdoc-openapi",
        "Implement request rate limiting with bucket4j or resilience4j",
        "Add comprehensive integration tests for each service",
        "Consider implementing CQRS for read-heavy operations",
        "Add health check endpoints via Spring Actuator",
    ],
    "complexity_analysis": {
        "average_complexity": 4.2,
        "complex_files": [
            {"file_path": "src/main/java/com/example/app/services/rental/service/RentalServiceImpl.java",
             "score": 8, "notes": "High complexity due to rental business logic including inventory checks, date calculations, and transaction management."},
            {"file_path": "src/main/java/com/example/app/services/catalog/repository/custom/CustomActorRepositoryImpl.java",
             "score": 7, "notes": "Complex QueryDSL predicate construction for dynamic actor search with multiple optional filters."},
            {"file_path": "src/main/java/com/example/app/common/security/JwtAuthenticationFilter.java",
             "score": 6, "notes": "Security filter with token validation, user details loading, and exception handling."},
            {"file_path": "src/main/java/com/example/app/services/catalog/domain/dto/FilmDto.java",
             "score": 6, "notes": "Large DTO with many fields, nested objects, custom serializers, and HATEOAS links."},
            {"file_path": "src/main/java/com/example/app/common/exception/GlobalExceptionHandler.java",
             "score": 5, "notes": "Multiple exception handler methods for different error types."},
        ],
        "dependencies": [
            "org.springframework.boot:spring-boot-starter-web",
            "org.springframework.boot:spring-boot-starter-data-jpa",
            "org.springframework.boot:spring-boot-starter-security",
            "org.springframework.boot:spring-boot-starter-data-redis",
            "org.springframework.boot:spring-boot-starter-validation",
            "com.querydsl:querydsl-jpa",
            "io.jsonwebtoken:jjwt-api",
            "org.mapstruct:mapstruct",
            "mysql:mysql-connector-java",
        ],
    },
    "chunk_analyses": [
        {"file_path": "src/main/java/com/example/app/services/catalog/controller/ActorController.java",
         "summary": "REST controller providing CRUD endpoints for Actor entities with HATEOAS support.",
         "purpose": "Expose actor management through RESTful API endpoints.",
         "key_methods": [
             {"name": "getActorList", "signature": "ResponseEntity<CollectionModel<ActorDto>> getActorList(Pageable pageable)",
              "description": "Retrieves paginated list of actors", "complexity": 3},
             {"name": "addActor", "signature": "ResponseEntity<Void> addActor(@RequestBody ActorDto.ActorRequest model)",
              "description": "Creates new actor", "complexity": 4},
         ],
         "dependencies": ["ActorService", "ActorRepresentationModelAssembler"],
         "complexity_score": 4, "complexity_notes": "Moderate complexity from HATEOAS assembly and pagination."},
        {"file_path": "src/main/java/com/example/app/services/rental/service/RentalServiceImpl.java",
         "summary": "Service implementing rental business logic with inventory management.",
         "purpose": "Encapsulate rental business rules and transaction management.",
         "key_methods": [
             {"name": "createRental", "signature": "RentalDto createRental(RentalDto dto)",
              "description": "Creates rental with inventory validation", "complexity": 7},
             {"name": "returnRental", "signature": "RentalDto returnRental(Long id)",
              "description": "Processes return with inventory update", "complexity": 6},
         ],
         "dependencies": ["RentalRepository", "InventoryRepository"],
         "complexity_score": 8, "complexity_notes": "High complexity from business rules, transactions, and date calculations."},
        {"file_path": "src/main/java/com/example/app/common/security/JwtAuthenticationFilter.java",
         "summary": "JWT filter validating tokens on every request.",
         "purpose": "Enforce stateless JWT authentication across all endpoints.",
         "key_methods": [
             {"name": "doFilterInternal", "signature": "void doFilterInternal(HttpServletRequest req, HttpServletResponse res, FilterChain chain)",
              "description": "Validates JWT from Authorization header", "complexity": 6},
         ],
         "dependencies": ["JwtTokenProvider", "JpaUserDetailsService"],
         "complexity_score": 6, "complexity_notes": "Security-critical code with token parsing and validation."},
        {"file_path": "src/main/java/com/example/app/services/catalog/repository/custom/CustomActorRepositoryImpl.java",
         "summary": "Custom QueryDSL repository for dynamic actor search.",
         "purpose": "Flexible query construction beyond standard Spring Data methods.",
         "key_methods": [
             {"name": "searchActors", "signature": "Page<ActorEntity> searchActors(String name, Pageable pageable)",
              "description": "Dynamic actor search with optional filters", "complexity": 5},
         ],
         "dependencies": ["QueryDSL", "JPAQueryFactory"],
         "complexity_score": 7, "complexity_notes": "Complex predicate construction with null-safe filters."},
    ],
}


