"""
Stage 2 — Code preprocessor: filter, categorize, and clean before chunking.

Responsibilities:
    1. Separate source files from non-source files
    2. Skip generated/auto-generated code
    3. Skip binary-ish or minified files
    4. Clean source code (normalize whitespace, strip blank lines)
    5. Categorize files for the LLM prompt context
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from src.models import Language, SourceFile


# ── File categories ──

# Only these languages get full AST parsing and LLM analysis
SOURCE_LANGUAGES = {
    Language.JAVA, Language.PYTHON, Language.GO,
    Language.JAVASCRIPT, Language.JSX,
    Language.TYPESCRIPT, Language.TSX,
}

# Extensions that are source code
SOURCE_EXTENSIONS = {
    ".java", ".py", ".go", ".js", ".jsx", ".ts", ".tsx", ".kt",
    ".rs", ".rb", ".cs", ".cpp", ".c", ".h", ".hpp",
}

# Extensions that are config/build (kept as context, not analyzed)
CONFIG_EXTENSIONS = {
    ".xml", ".yml", ".yaml", ".json", ".toml",
    ".properties", ".gradle", ".kts", ".cfg", ".ini", ".env",
    ".sql", ".md", ".rst", ".txt",
}

# Extensions to always skip
SKIP_EXTENSIONS = {
    ".class", ".pyc", ".pyo", ".o", ".so", ".dll", ".exe",
    ".jar", ".war", ".ear",
    ".png", ".jpg", ".jpeg", ".gif", ".svg", ".ico",
    ".woff", ".woff2", ".ttf", ".eot",
    ".zip", ".tar", ".gz", ".rar", ".7z",
    ".pdf", ".doc", ".docx",
    ".lock", ".sum",
    ".min.js", ".min.css",
}

# Auto-generated file markers (skip if found in first 5 lines)
GENERATED_MARKERS = [
    "auto-generated",
    "automatically generated",
    "generated by",
    "do not edit",
    "do not modify",
    "this file is generated",
    "generated code",
    "@generated",
    "code generated by",
    "auto generated",
]

# File names to always skip
SKIP_FILENAMES = {
    ".gitignore", ".gitattributes", ".gitmodules",
    ".dockerignore", "dockerfile", "docker-compose.yml",
    "license", "licence", "changelog", "contributing",
    "makefile", "cmakelists.txt",
    ".editorconfig", ".prettierrc", ".eslintrc",
    "jest.config.js", "webpack.config.js", "babel.config.js",
    "tsconfig.json", "jsconfig.json",
}


@dataclass
class PreprocessorResult:
    """Output from the preprocessor."""
    source_files: list[SourceFile]    # Source code files (analyzed by LLM)
    config_files: list[SourceFile]    # Config files (context only, not chunked)
    skipped_count: int                # How many files were filtered out
    skipped_reasons: dict[str, int]   # Why files were skipped

    @property
    def total_source_lines(self) -> int:
        return sum(f.line_count for f in self.source_files)

    @property
    def total_config_lines(self) -> int:
        return sum(f.line_count for f in self.config_files)


def preprocess(files: list[SourceFile]) -> PreprocessorResult:
    """
    Filter and clean a list of discovered files.

    Returns source files ready for chunking, plus config files for context.
    """
    source_files: list[SourceFile] = []
    config_files: list[SourceFile] = []
    skipped_reasons: dict[str, int] = {}

    def skip(reason: str):
        skipped_reasons[reason] = skipped_reasons.get(reason, 0) + 1

    for f in files:
        # 1. Skip by extension
        ext = _ext(f.relative_path)
        if ext in SKIP_EXTENSIONS:
            skip("skip_extension")
            continue

        # 2. Skip by filename
        fname = f.relative_path.rsplit("/", 1)[-1].lower()
        if fname in SKIP_FILENAMES:
            skip("skip_filename")
            continue

        # 3. Skip generated files
        if _is_generated(f.content):
            skip("generated")
            continue

        # 4. Skip minified files (very long lines, no newlines)
        if f.line_count < 5 and f.size_bytes > 5000:
            skip("minified")
            continue

        # 5. Skip files that are mostly binary (high ratio of non-printable chars)
        if _mostly_binary(f.content):
            skip("binary_content")
            continue

        # ── Categorize ──
        if ext in SOURCE_EXTENSIONS and f.language in SOURCE_LANGUAGES:
            # Source code -> clean and add for analysis
            f.content = _clean_source(f.content)
            f.line_count = f.content.count("\n") + (1 if f.content and not f.content.endswith("\n") else 0)
            source_files.append(f)

        elif ext in CONFIG_EXTENSIONS or f.language == Language.UNKNOWN:
            # Config/build files -> kept for context, not chunked
            config_files.append(f)

        else:
            # Everything else -> skip
            skip("not_source_or_config")

    result = PreprocessorResult(
        source_files=source_files,
        config_files=config_files,
        skipped_count=sum(skipped_reasons.values()),
        skipped_reasons=skipped_reasons,
    )

    return result


# ── Cleaning functions ──

def _clean_source(content: str) -> str:
    """
    Light cleanup for source code before LLM analysis.
    Does NOT change line numbers (important for AST parsing).
    """
    lines = content.split("\n")
    cleaned: list[str] = []
    blank_count = 0

    for line in lines:
        # Collapse runs of 3+ blank lines into 1
        if line.strip() == "":
            blank_count += 1
            if blank_count <= 2:
                cleaned.append("")
        else:
            blank_count = 0
            # Remove trailing whitespace
            cleaned.append(line.rstrip())

    return "\n".join(cleaned)


def _is_generated(content: str) -> bool:
    """Check if a file has auto-generated markers in the first 10 lines."""
    head = "\n".join(content.split("\n")[:10]).lower()
    return any(marker in head for marker in GENERATED_MARKERS)


def _mostly_binary(content: str, threshold: float = 0.3) -> bool:
    """Check if content has too many non-printable characters."""
    if not content:
        return False
    sample = content[:2000]
    non_printable = sum(1 for c in sample if ord(c) < 32 and c not in "\n\r\t")
    return (non_printable / len(sample)) > threshold


def _ext(path: str) -> str:
    """Get lowercase file extension."""
    dot = path.rfind(".")
    return path[dot:].lower() if dot != -1 else ""
